---
roles:
  - name: geerlingguy.ansible
    version: 2.0.2
  - name: geerlingguy.certbot
    version: 3.0.3
  - name: geerlingguy.docker
    version: 2.7.0
  - name: geerlingguy.java
    version: 1.9.7
  - name: geerlingguy.jenkins
    version: 4.3.0
  - name: geerlingguy.git
    version: 3.0.0
  - name: geerlingguy.nginx
    version: 2.7.0
  - name: geerlingguy.security
    version: 1.9.0
  - name: geerlingguy.firewall
    version: 2.5.0
  - name: geerlingguy.pip
    version: 1.3.0
